# Generated by Django 4.2.23 on 2025-08-16 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignBusRouteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='BusRouteTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Route_ID', models.CharField(blank=True, max_length=10, null=True)),
                ('Source', models.CharField(blank=True, max_length=30, null=True)),
                ('Destination', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusStopTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Stop_name', models.CharField(blank=True, max_length=30, null=True)),
                ('Landmark', models.CharField(blank=True, max_length=30, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='')),
                ('BUSROUTE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busroutetable')),
            ],
        ),
        migrations.CreateModel(
            name='BusTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Busname', models.CharField(blank=True, max_length=30, null=True)),
                ('Bus_NO', models.CharField(blank=True, max_length=12, null=True)),
                ('Capacity', models.IntegerField(blank=True, null=True)),
                ('RC_NO', models.CharField(blank=True, max_length=15, null=True)),
                ('Photo', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='LoginTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=30, null=True)),
                ('Password', models.CharField(blank=True, max_length=30, null=True)),
                ('UserType', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PassangerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Contact_NO', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='WalletTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Balance', models.FloatField()),
                ('DateTime', models.DateTimeField()),
                ('Amount', models.FloatField()),
                ('Debit', models.FloatField()),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='TripStatustable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(blank=True, max_length=12, null=True)),
                ('ASSIGN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.assignbusroutetable')),
            ],
        ),
        migrations.CreateModel(
            name='TicketTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField()),
                ('Status', models.CharField(blank=True, max_length=12, null=True)),
                ('Ticket_No', models.IntegerField(blank=True, max_length=3, null=True)),
                ('Paid_amount', models.FloatField()),
                ('Count', models.IntegerField(blank=True, max_length=12, null=True)),
                ('PASSANGER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable')),
                ('STOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busstoptable')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Contact_NO', models.BigIntegerField(blank=True, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Email', models.CharField(blank=True, max_length=30, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='FeedbackTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Feedback', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable')),
            ],
        ),
        migrations.CreateModel(
            name='DriverTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Address', models.CharField(blank=True, max_length=30, null=True)),
                ('Licence_NO', models.CharField(blank=True, max_length=16, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Contact_NO', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Status', models.CharField(blank=True, max_length=8, null=True)),
                ('Latitude', models.FloatField(blank=True, null=True)),
                ('Longitude', models.FloatField(blank=True, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='CondotorTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Age', models.IntegerField(blank=True, null=True)),
                ('Contact_NO', models.BigIntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=2, null=True)),
                ('Address', models.CharField(blank=True, max_length=50, null=True)),
                ('LOGIN', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable')),
            ],
        ),
        migrations.CreateModel(
            name='ComplaintTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint', models.CharField(blank=True, max_length=100, null=True)),
                ('Reply', models.CharField(blank=True, max_length=100, null=True)),
                ('Date', models.DateField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('USER', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable')),
            ],
        ),
        migrations.CreateModel(
            name='BookingTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(blank=True, max_length=30, null=True)),
                ('Payment_Amount', models.FloatField()),
                ('Date', models.DateTimeField()),
                ('BUS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('BUSSTOP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busstoptable')),
            ],
        ),
        migrations.AddField(
            model_name='assignbusroutetable',
            name='BUS',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable'),
        ),
        migrations.AddField(
            model_name='assignbusroutetable',
            name='CONDOCTOR',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.condotortable'),
        ),
        migrations.AddField(
            model_name='assignbusroutetable',
            name='DRIVER',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.drivertable'),
        ),
        migrations.AddField(
            model_name='assignbusroutetable',
            name='ROUTE',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busroutetable'),
        ),
    ]
