# Generated by Django 4.2.23 on 2025-08-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettable',
            name='Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='Ticket_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
