# Generated by Django 4.2.23 on 2025-08-31 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustable',
            name='OWNER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.ownertable'),
        ),
        migrations.AddField(
            model_name='bustable',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='Count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='Ticket_No',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
