# Generated by Django 4.2.23 on 2025-08-31 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0002_bustable_owner_bustable_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bustable',
            name='OWNER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.ownertable'),
            preserve_default=False,
        ),
    ]
