# Generated by Django 4.2.23 on 2025-08-28 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0002_alter_tickettable_count_alter_tickettable_ticket_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='bustable',
            name='LOGIN',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
            preserve_default=False,
        ),
    ]
