# Generated by Django 4.2.23 on 2025-09-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0003_alter_bustable_owner'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CondotorTable',
            new_name='CondoctorTable',
        ),
        migrations.RemoveField(
            model_name='assignbusroutetable',
            name='CONDOCTOR',
        ),
        migrations.RemoveField(
            model_name='assignbusroutetable',
            name='DRIVER',
        ),
        migrations.RemoveField(
            model_name='busroutetable',
            name='Route_ID',
        ),
        migrations.AlterField(
            model_name='assignbusroutetable',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='busstoptable',
            name='Photo',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='busstoppic/'),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='Date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='Date',
            field=models.DateTimeField(auto_created=True),
        ),
        migrations.AlterField(
            model_name='tripstatustable',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
