# Generated by Django 4.2.23 on 2025-09-01 06:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0004_rename_condotortable_condoctortable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignbusroutetable',
            name='End_Time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignbusroutetable',
            name='Start_Time',
            field=models.TimeField(default=datetime.datetime(2025, 9, 1, 6, 16, 45, 85169, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignbusroutetable',
            name='BUS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable'),
        ),
        migrations.AlterField(
            model_name='assignbusroutetable',
            name='ROUTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busroutetable'),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='BUS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable'),
        ),
        migrations.AlterField(
            model_name='bookingtable',
            name='BUSSTOP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busstoptable'),
        ),
        migrations.AlterField(
            model_name='busstoptable',
            name='BUSROUTE',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busroutetable'),
        ),
        migrations.AlterField(
            model_name='bustable',
            name='OWNER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.ownertable'),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='BUS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable'),
        ),
        migrations.AlterField(
            model_name='complainttable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable'),
        ),
        migrations.AlterField(
            model_name='condoctortable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
        ),
        migrations.AlterField(
            model_name='drivertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='BUS',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable'),
        ),
        migrations.AlterField(
            model_name='feedbacktable',
            name='USER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable'),
        ),
        migrations.AlterField(
            model_name='ownertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
        ),
        migrations.AlterField(
            model_name='passangertable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='PASSANGER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.passangertable'),
        ),
        migrations.AlterField(
            model_name='tickettable',
            name='STOP',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busstoptable'),
        ),
        migrations.AlterField(
            model_name='tripstatustable',
            name='ASSIGN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.assignbusroutetable'),
        ),
        migrations.AlterField(
            model_name='wallettable',
            name='LOGIN',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.logintable'),
        ),
    ]
