# Generated by Django 4.2.23 on 2025-09-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0005_assignbusroutetable_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignbusroutetable',
            name='Status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
