# Generated by Django 4.2.23 on 2025-09-02 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0007_alter_bustable_bus_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDriver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('CONDUCTER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.condoctortable')),
            ],
        ),
    ]
