# Generated by Django 4.2.23 on 2025-09-02 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0008_assigndriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assigndriver',
            name='CONDUCTER',
        ),
        migrations.AddField(
            model_name='assigndriver',
            name='DRIVER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.drivertable'),
        ),
        migrations.CreateModel(
            name='AssignConducter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BUS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('CONDUCTER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.condoctortable')),
            ],
        ),
    ]
