# Generated by Django 4.2.23 on 2025-09-02 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0009_remove_assigndriver_conducter_assigndriver_driver_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('Date', models.DateField(auto_now_add=True)),
                ('BUS', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.bustable')),
                ('Conducter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.condoctortable')),
                ('DRIVER', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.drivertable')),
            ],
        ),
        migrations.RemoveField(
            model_name='assigndriver',
            name='BUS',
        ),
        migrations.RemoveField(
            model_name='assigndriver',
            name='DRIVER',
        ),
        migrations.DeleteModel(
            name='AssignConducter',
        ),
        migrations.DeleteModel(
            name='AssignDriver',
        ),
    ]
