# Generated by Django 4.2.23 on 2025-09-08 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0010_assigntable_remove_assigndriver_bus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='condoctortable',
            name='OWNER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.ownertable'),
        ),
        migrations.AddField(
            model_name='drivertable',
            name='OWNER',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.ownertable'),
        ),
    ]
