# Generated by Django 4.2.23 on 2025-09-20 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BuzbeeApp', '0011_condoctortable_owner_drivertable_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.TimeField()),
                ('Status', models.CharField(blank=True, max_length=20, null=True)),
                ('ASSIGNBUSROUTE', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.assignbusroutetable')),
                ('BUSSTOP', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='BuzbeeApp.busstoptable')),
            ],
        ),
    ]
